apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: orders-demo

resources:
  - namespace.yaml
  - postgres-init-configmap.yaml
  - postgres.yaml
  - redis.yaml
  - redis-seed-job.yaml
  - pricing-service.yaml
  - orders-service.yaml

images:
  - name: orders-service
    newTag: local
  - name: pricing-service
    newTag: local
